# Generated by Django 4.2.20 on 2025-04-19 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
