# Generated by Django 4.2.20 on 2025-04-30 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergame',
            name='age',
        ),
        migrations.RemoveField(
            model_name='usergame',
            name='nickname',
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victories', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
