# Generated by Django 4.2.20 on 2025-05-02 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0005_remove_usergame_age_remove_usergame_nickname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticasJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victorias', models.IntegerField(default=0)),
                ('juegos_jugados', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estadistica jugador',
                'verbose_name_plural': 'Estadisticas jugadores',
            },
        ),
        migrations.AlterModelOptions(
            name='playerstats',
            options={'verbose_name': 'Player Stat', 'verbose_name_plural': 'Player Stats'},
        ),
        migrations.DeleteModel(
            name='UserGame',
        ),
    ]
